ingress:
  installed: true

certManager:
  installed: true
  letsEncryptClusterIssuer:
    installed: true
    email: "user1@emk-solutions.net"

gitlabRunner:
  installed: true

prometheus:
  installed: true

elasticStack:
  installed: false

sentry:
  installed: false